github:
  description: "Apache Grails Website"
  homepage: https://grails.apache.org/
  features:
    issues: true

# Automatically publish to https://grails.apache.org/
publish: 
  whoami:  asf-site-production
