github:
  description: "Apache Grails Website & Documentation"
  homepage: https://grails.apache.org/
  features:
    wiki: false
    issues: true
    projects: false
    discussions: false
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  # GitHub related
  commits: commits@grails.apache.org
  jobs: notifications@grails.apache.org
  pullrequests_status: notifications@grails.apache.org
  pullrequests_comment: notifications@grails.apache.org
  pullrequests_bot_dependabot: notifications@grails.apache.org
  issues: notifications@grails.apache.org
  issues_status: notifications@grails.apache.org
  issues_comment: notifications@grails.apache.org
  discussions: users@grails.apache.org
# Automatically publish to https://grails.apache.org/
publish:
  whoami: asf-site-production
