github:
  description: "Apache Grails Website"
  homepage: https://grails.apache.org/
  features:
    wiki: false
    issues: true
    projects: false
    discussions: false
notifications:
  # GitHub related
  commits: commits@grails.apache.org
  jobs: notifications@grails.apache.org
  pullrequests_status: notifications@grails.apache.org
  pullrequests_comment: notifications@grails.apache.org
  pullrequests_bot_dependabot: notifications@grails.apache.org
  issues: notifications@grails.apache.org
  issues_status: notifications@grails.apache.org
  issues_comment: notifications@grails.apache.org
  discussions: users@grails.apache.org
# Automatically publish to https://grails.apache.org/
publish: 
  whoami:  asf-site-production
